### ISSUE TITLE
Book link doesn't work

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/didcomm.org#29]
It looks like the /book/v2 page is a 404. It might work to change the README.md to index.md but I'm not sure. Thoughts?

**Comment by brianorwhatever** [comment]
possibly moving into the `/site/content` directory will help

**Comment by dhh1128** [comment]
I'll take this.

**Comment by brianorwhatever** [comment]
lgtm however we should probably add a header or something in the future so viewers aren't lost when they land on the book. closing
