### ISSUE TITLE
registered context is 404

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/didcomm.org#9]
https://w3c.github.io/did-spec-registries/#didcommmessaging

This is caused by gh-pages branch not containing `/messaging/contexts/v2/index.json` cc @awoie

**Comment by awoie** [comment]
Thanks for pointing that out. We had a larger PR recently. Perhaps, that changed some things. I'll check.

**Comment by TelegramSam** [comment]
The file is in the repo here:
https://github.com/decentralized-identity/didcomm.org/blob/main/docs/messaging/contexts/v2/index.json
But the file is not being published by the current build script to the proper location, which is here:
/messaging/contexts/v2/index.json

The gatsby build scripts need to be updated to publish this file to the proper location.

**Comment by TelegramSam** [comment]
I partially fixed this with #25 , but now there is an automatically inserted header placed there by gatsby. I'll see if I can find a way to turn that off.

**Comment by brianorwhatever** [comment]
this appears to be working

https://didcomm.org/messaging/contexts/v2 resolves
https://didcomm.org/messaging/contexts/v2/index.json resolves

recommend close?
