### ISSUE TITLE
[Question] Sanity check on mismatch between URLs and message type URIs.

### ISSUE THREAD

**Issue by pauldesmondparker** [decentralized-identity/didcomm.org#96]
# Assumption
I'm assuming that there should be some correspondence between the published `https://didcomm.org/` URL Paths and the URI defined within.

# Current Behavior
Examples (not attempt to be exhaustive):
| URL                           | Message Type URI                                       |
|-------------------------------|------------------------------------------------|
| https://didcomm.org/pickup/3.0/ | https://didcomm.org/messagepickup/3.0/status |
| https://didcomm.org/mediator-coordination/3.0/ | https://didcomm.org/coordinate-mediation/3.0/mediate-request |

![image](https://github.com/decentralized-identity/didcomm.org/assets/114397409/063b574c-3062-4b27-ade5-07eba0650156)

# Expected Behavior
| URL                           | Message Type URI                                       |
|-------------------------------|------------------------------------------------|
| https://didcomm.org/messagepickup/3.0/ | https://didcomm.org/messagepickup/3.0/status |
| https://didcomm.org/coordinate-mediation/3.0/ | https://didcomm.org/coordinate-mediation/3.0/mediate-request |

**Comment by dccboss** [comment]
@TelegramSam And `messagepickup`?

**Comment by dbluhm** [comment]
@dccboss fixed in #98 :slightly_smiling_face:
